### ISSUE TITLE
Clone layout button so it doesn't disappear and reappear

### ISSUE THREAD

**Issue by hellomichael** [edirpedro/acf-flexible-content-modal#10]
Amazing plugin @edirpedro. 

Would be a nice UX improvement if the layout button didn't completely disappear and reappear when opening and closing the modal.

Possibly cloning the button and removing the -modal class when open?

**Comment by edirpedro** [comment]
I see, but the modal you see on screen is exactly the layout element with a different CSS to look like a modal. To make it stay on the list and open the modal, I'd have to clone the layout and this could cause errors for third-party plugins interacting with that layout.
