### ISSUE TITLE
Show value from module when collapsed

### ISSUE THREAD

**Issue by louiswalch** [edirpedro/acf-flexible-content-modal#2]
This is a great extension and just what I was looking for. Really cleans up the editing interface for Flexible Content pages.

If I had to make one suggestion, it would be nice if you could assign a field from the module's content to be shown in the collapsed state. For very complex pages, there could be multiple instances of the same module. Being able to choose to shown the 'Title' along side the type of module would really go a long way.

**Comment by edirpedro** [comment]
Thank you. For your suggestion, ACF already has this feature, take a look on link below.

https://www.advancedcustomfields.com/resources/acf-fields-flexible_content-layout_title/

**Comment by louiswalch** [comment]
Oh nice! Thanks.
