### ISSUE TITLE
Add composer.json

### ISSUE THREAD

**Issue by ruscon** [edirpedro/acf-flexible-content-modal#3]
sample
https://github.com/nlemoine/acf-country/blob/master/composer.json

**Comment by edirpedro** [comment]
File added. I hope it's not wrong because I don't use compuser here.

**Comment by ruscon** [comment]
Can you register it in https://packagist.org/ ?
You can set auto updating once from the git
See https://packagist.org/about -> "How to update packages?"

Can u do this, please.

**Comment by edirpedro** [comment]
Sure, up and running ;-)
