### ISSUE TITLE
Choose where to use FC Modal

### ISSUE THREAD

**Issue by edirpedro** [edirpedro/acf-flexible-content-modal#4]
Two guys were using FC nested like in this screenshots below. They are trying to create a page builder, as complex as some plugins like Visual Compuser and Page Builder by SiteOrigin works. I think this is a bad idea to use with ACF, FC fields were not made with this idea in mind.

![7ce61a34-a282-11e6-9ed1-372e024052ee](https://user-images.githubusercontent.com/831507/27436903-095df996-5737-11e7-9b97-b3db93a88157.png)

![modal](https://user-images.githubusercontent.com/831507/27436434-aa5dad3e-5735-11e7-8930-d9e9fcdd6753.jpg)

## Details

- My idea is to create an option for FC fields to select if that field should use a modal or not.
- The modal cannot affect a FC nested.
- How complex is to use CSS to create the modal in this situation?
- With this feature, developers can open two modals at the same time, modal above modal, this is not user friendly.
- Issue  #1 "looks like FC field is not intended to be nested like the Repeater field"

**Comment by hwkdev** [comment]
Easy fix for this problem, simply make an exception for the `display: none` in nested flexible content in modals ;)

style.css:26 - edit to:
```
/* All collapsed */
.inside.acf-fields.-top > .acf-field-flexible-content > .acf-input > .acf-flexible-content > .values > .layout:not(.-modal) > .acf-fc-layout-handle {
	border-bottom-width: 0;
}
.inside.acf-fields.-top > .acf-field-flexible-content > .acf-input > .acf-flexible-content > .values > .layout:not(.-modal) > .acf-fields,
.inside.acf-fields.-top > .acf-field-flexible-content > .acf-input > .acf-flexible-content > .values > .layout:not(.-modal) > .acf-table {
	display: none;
}
```
